# Generated by Django 5.2.5 on 2025-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
