# Generated by Django 5.2.5 on 2025-08-12 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_internship_application_activitylog_bookmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='internship',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('internship_posted', 'Internship Posted'), ('internship_updated', 'Internship Updated'), ('internship_deleted', 'Internship Deleted'), ('application_submitted', 'Application Submitted'), ('application_status_changed', 'Application Status Changed'), ('application_withdrawn', 'Application Withdrawn'), ('bookmark_added', 'Bookmark Added'), ('bookmark_removed', 'Bookmark Removed'), ('profile_updated', 'Profile Updated'), ('profile_picture_updated', 'Profile Picture Updated'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('password_changed', 'Password Changed')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('internship', 'user')},
        ),
    ]
