# Generated by Django 5.2.5 on 2025-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
