# Generated by Django 5.2.5 on 2025-08-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
