# Generated by Django 5.2.5 on 2025-08-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_profile_profile_picture_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter')], max_length=10),
        ),
    ]
